config/routes.rb
Rails.application.routes.draw do
  get 'welcome/home'
  get 'welcome/about'
  resources :articles
  root 'welcome#home'

  get 'signup', to: 'users#new'
  resources :users  #, except: [:new]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
 belongs_to :user
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord

  has_many :articles
  before_save { self.email = email.downcase }
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                  length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { minimum: 5, maximum: 255 },
                uniqueness: { case_sensitive: false },
                format: { with: VALID_EMAIL_REGEX }

  has_secure_password 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json

  def index
    # @articles = Article.all
    # Pagination Implementation
    #loads default number of item per page (20 or 30)
    @articles = Article.paginate(page: params[:page], per_page: 2)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #
    # id = params[:id].to_i
    # id = id -8
    # @article = Article.find(id)
     # @article = Article.find(params[:id])

  end

  # GET /articles/new
  def new
     @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create



    @article = Article.new(article_params)

# pansuman tedbir
     @article.user = User.first

    respond_to do |format|
      if @article.save

         format.html { redirect_to @article , notice: 'YESSSS !Article was successfully created.' }
          # format.html { redirect_to "https://www.google.com" , notice: 'YESSSS !Article was successfully created.' }
         # flash[:notice] = "HOPPALA"
        # format.html { redirect_to new_article_path, notice: 'YESSSS !Article was successfully created.' }
        # format.json { render :show, status: :created, location: @article }
        format.json { render :action => "show", status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      # format.html { redirect_to articles_url }
       format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)

    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json

  def index
    # @users = User.all
    # paginate
    @users = User.paginate(page: params[:page], per_page: 2)

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #
    # id = params[:id].to_i
    # id = id -8
    # @article = Article.find(id)
     # @article = Article.find(params[:id])
     @user_articles = @user.articles.paginate(page: params[:page], per_page: 1)

  end

  # GET /articles/new
  def new
     @user = User.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create



    @user = User.new(user_params)


    respond_to do |format|
      if @user.save

         format.html { redirect_to @user , notice: 'User was successfully created.' }
        format.json { render :action => "show", status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      # format.html { redirect_to articles_url }
       format.html { redirect_to user_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)

    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <!-- <th colspan="3"></th> -->

      <th>Description</th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% obj.each do |article| %>


      <tr>
        <td>Created by: <%=article.user.username if article.user %>, <%=time_ago_in_words(article.created_at)%>  ago </td>
          <td><%= gravatar_for article.user if article.user %></td>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/_dummytail.html.erb
<h1>This is a useless tail</h1>
<h1>This is a useless tail</h1>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article id: <%= @article.id %></h1>

<% if @article.errors.any? %>
<h2>The following error prevents the article to be saved </h2>
  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1>Create an article</h1>

<% if @article.errors.any? %>
<h2>The following error prevents the article to be saved </h2>
  <ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>



<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

<%= render 'dummytail', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= gravatar_for @article.user %>
  <%= link_to @article.user.username,  user_path(@article.user)   %>
</p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>


 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!-- This a wrapper file file for views in the applicaiton -->

<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render 'layouts/navigation' %>


    <!-- all other views in the app get served in this area  -->

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit(@user.new_record? ? "Sign up" : "Update your account")%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit your account: <%= @user.id %></h1>

<% if @user.errors.any? %>
<h2>The following error prevents this user to be saved </h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>


<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
    <%= will_paginate %>
</div>

<h1>All Alpha Bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Created: </th>
      <th>  </th>
      <th>Number of Articles </th>
      <th>User Name </th>
      <!-- <th colspan="3"></th> -->

      <th>Email </th>
      <!-- <th colspan="3"></th> -->
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>


      <tr>
        <td> <%=time_ago_in_words(user.created_at) if user.created_at%>  ago </td>
        <td><%= gravatar_for user %></td>
        <td><%= user.articles.count %> article</td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Signup for Alpha Blog </h1>

<% if @user.errors.any? %>
<h2>The following error prevents the user to be saved </h2>
  <ul>
  <% @user.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
<% end %>



<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Welcome to <%= @user.username %>'s page </strong>
    <%= gravatar_for @user, size: 150%>

</p>

<p>
  <strong>E-mail:</strong>
  <%= @user.email %>
</p>

<p><h2> <%= @user.username %>s Articles: </h2>

  <div align="center">
      <%= will_paginate @user_articles%>
  </div>
<%=render 'articles/article', obj: @user_articles%>





<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<h1>This is the about page of my blog app</h1>

 <%= link_to 'Alpha Blog', articles_path  %>
 <%= link_to 'Home',  welcome_home_path  %>

app/views/welcome/home.html.erb
<h1>This is the home page of my blog app</h1>

 <%= link_to 'Alpha Blog', articles_path  %>
 <%= link_to 'About',  welcome_about_path  %>